name: Ukraine Alarm Map Clean
version: "1.4.12"
slug: ukraine_alarm_map_clean
description: Clean interactive Ukraine air-raid map proxy for Home Assistant
url: https://map.ukrainealarm.com/
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
init: false
ingress: true
ingress_port: 8765
ingress_stream: true
panel_icon: mdi:map-legend
panel_title: Тривоги України
panel_admin: false
options: {}
schema: {}
